// <auto-generated />
using System;
using Microsoft.Build.Logging.BuildDb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microsoft.Build.Logging.BuildDb.Migrations
{
    [DbContext(typeof(BuildDbContext))]
    [Migration("20190415010142_RootBuild")]
    partial class RootBuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Microsoft.Build.Logging.BuildDb.Model.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("StartTime");

                    b.Property<bool>("Succeeded");

                    b.HasKey("Id");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Microsoft.Build.Logging.BuildDb.Model.BuildProperty", b =>
                {
                    b.Property<int>("BuildId");

                    b.Property<int>("PropertyId");

                    b.HasKey("BuildId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("BuildProperties");
                });

            modelBuilder.Entity("Microsoft.Build.Logging.BuildDb.Model.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Microsoft.Build.Logging.BuildDb.Model.BuildProperty", b =>
                {
                    b.HasOne("Microsoft.Build.Logging.BuildDb.Model.Build", "Build")
                        .WithMany("Environment")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.Build.Logging.BuildDb.Model.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
